In [ ]:
# import logging

# #configure the basic config settings
# logging.basicConfig(
#     filename='app.log',
#     filemode='W',
#     level=logging.DEBUG,
#     format='%(asctime)s-%(name)s-%(levelname)s-%(message)',
# datefmt='%Y-%m-%d %H:%M:%S' 

    
# )

# ##log messages
# logging.debug("This is a debug message")
# logging.info("This is a info message")
# logging.warning("This is a warning message")
# logging.error("This is a error message")
# logging.critical("This is a critical message")

ValueError: invalid mode: 'W'

In [ ]:
##configuring logging
logging.basicConfig(
    level=logging.DEBUG,
    format='%(asctime)s-%(name)s-%(levelname)s-%(message)',
datefmt='%Y-%m-%d %H:%M:%S' 

    
)

In [ ]:
pip install bs4

Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Requirement already satisfied: beautifulsoup4 in c:\users\3lokm\appdata\local\programs\python\python310\lib\site-packages (from bs4) (4.15.0)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\3lokm\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4->bs4) (2.9.1)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\3lokm\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4->bs4) (4.15.0)
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Installing collected packages: bs4
Successfully installed bs4-0.0.2
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import threading
import requests
from bs4 import BeautifulSoup
url=['https://www.udemy.com/course/complete-machine-learning-nlp-bootcamp-mlops-deployment/learn/lecture/44469918#overview',
    'https://supabase.com/dashboard/project/fetqsatawztrnqnoneqy/storage/analytics']
def fetch_content(url):
    response=requests.get(url)
    soup=BeautifulSoup(response.content,'html.parser')
    print(f"Fetched {len(response.content)} characters from {url}")
thread=[]
for urls in url:
    t1=threading.Thread(target=fetch_content,args=(urls,))
    thread.append(t1)
    t1.start()

Fetched 19258 characters from https://supabase.com/dashboard/project/fetqsatawztrnqnoneqy/storage/analytics
Fetched 280086 characters from https://www.udemy.com/course/complete-machine-learning-nlp-bootcamp-mlops-deployment/learn/lecture/44469918#overview

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
student_data=[
  [1, 15],
  [2, 11],
  ['null', 11],
  [4, 20]
]
df=pd.DataFrame(student_data).rename(columns={0:"x",1:"y"})
df

      x   y
0     1  15
1     2  11
2  null  11
3     4  20

In [ ]:
df['x']=df['x'].drop_duplicates()

NameError: name 'df' is not defined

In [ ]:
df["z"]=df['y']*2

In [ ]:
df

   x   y   z
0  1  15  30
1  2  11  22
2  3  11  22
3  4  20  40

In [ ]:
df.loc[(df['x']==4,'y')]

3    20
Name: y, dtype: int64

In [ ]:
df[]