In [15]:
if 1+1==2:
    print("yes")
else:
    print("False")

yes

In [107]:
import notebook
print(notebook.__version__)

7.6.1

In [109]:
pip install jupyterlab-execute-time

Requirement already satisfied: jupyterlab-execute-time in .\appdata\local\programs\python\python310\lib\site-packages (3.3.0)
Requirement already satisfied: jupyterlab<5,>=4 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-execute-time) (4.6.2)
Requirement already satisfied: async-lru>=1.0.0 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<5,>=4->jupyterlab-execute-time) (2.3.0)
Requirement already satisfied: httpx<1,>=0.25.0 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<5,>=4->jupyterlab-execute-time) (0.28.1)
Requirement already satisfied: ipykernel!=6.30.0,>=6.5.0 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<5,>=4->jupyterlab-execute-time) (7.3.0)
Requirement already satisfied: jinja2>=3.0.3 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<5,>=4->jupyterlab-execute-time) (3.1.6)
Requirement already satisfied: jupyter-builder>=1.0.2 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<5,>=4->jupyterlab-execute-time) (1.2.1)
Requirement already satisfied: jupyter-core in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<5,>=4->jupyterlab-execute-time) (5.9.1)
Requirement already satisfied: jupyter-lsp>=2.0.0 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<5,>=4->jupyterlab-execute-time) (2.3.1)
Requirement already satisfied: jupyter-server<3,>=2.19.0 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<5,>=4->jupyterlab-execute-time) (2.20.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<5,>=4->jupyterlab-execute-time) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<5,>=4->jupyterlab-execute-time) (0.2.4)
Requirement already satisfied: packaging>=23.2 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<5,>=4->jupyterlab-execute-time) (25.0)
Requirement already satisfied: tomli>=1.2.2 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<5,>=4->jupyterlab-execute-time) (2.4.1)
Requirement already satisfied: tornado>=6.2.0 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<5,>=4->jupyterlab-execute-time) (6.5.5)
Requirement already satisfied: traitlets in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<5,>=4->jupyterlab-execute-time) (5.16.1)
Requirement already satisfied: typing-extensions>=4.4.0 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<5,>=4->jupyterlab-execute-time) (4.15.0)
Requirement already satisfied: anyio in .\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab<5,>=4->jupyterlab-execute-time) (4.14.1)
Requirement already satisfied: certifi in .\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab<5,>=4->jupyterlab-execute-time) (2025.11.12)
Requirement already satisfied: httpcore==1.* in .\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab<5,>=4->jupyterlab-execute-time) (1.0.9)
Requirement already satisfied: idna in .\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab<5,>=4->jupyterlab-execute-time) (3.11)
Requirement already satisfied: h11>=0.16 in .\appdata\local\programs\python\python310\lib\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.16.0)
Requirement already satisfied: argon2-cffi>=21.1 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (25.1.0)
Requirement already satisfied: jupyter-client>=7.4.4 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (8.9.1)
Requirement already satisfied: jupyter-events>=0.11.0 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.5.4)
Requirement already satisfied: nbconvert>=6.4.4 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (7.17.1)
Requirement already satisfied: nbformat>=5.3.0 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (5.10.4)
Requirement already satisfied: overrides>=5.0 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.26.0)
Requirement already satisfied: pywinpty!=3.0.4,>=2.0.1 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (3.0.5)
Requirement already satisfied: pyzmq>=24 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (27.1.0)
Requirement already satisfied: send2trash>=1.8.2 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (1.9.0)
Requirement already satisfied: babel>=2.10 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab<5,>=4->jupyterlab-execute-time) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.15.0)
Requirement already satisfied: jsonschema>=4.18.0 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab<5,>=4->jupyterlab-execute-time) (4.26.0)
Requirement already satisfied: requests>=2.31 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab<5,>=4->jupyterlab-execute-time) (2.32.5)
Requirement already satisfied: exceptiongroup>=1.0.2 in .\appdata\local\programs\python\python310\lib\site-packages (from anyio->httpx<1,>=0.25.0->jupyterlab<5,>=4->jupyterlab-execute-time) (1.3.1)
Requirement already satisfied: argon2-cffi-bindings in .\appdata\local\programs\python\python310\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (25.1.0)
Requirement already satisfied: comm>=0.1.1 in .\appdata\local\programs\python\python310\lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in .\appdata\local\programs\python\python310\lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<5,>=4->jupyterlab-execute-time) (1.8.21)
Requirement already satisfied: ipython>=7.23.1 in .\appdata\local\programs\python\python310\lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<5,>=4->jupyterlab-execute-time) (8.39.0)
Requirement already satisfied: matplotlib-inline>=0.1 in .\appdata\local\programs\python\python310\lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.2.2)
Requirement already satisfied: nest-asyncio2>=1.7.0 in .\appdata\local\programs\python\python310\lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<5,>=4->jupyterlab-execute-time) (1.7.2)
Requirement already satisfied: psutil>=5.7 in .\appdata\local\programs\python\python310\lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<5,>=4->jupyterlab-execute-time) (7.2.2)
Requirement already satisfied: colorama in .\appdata\local\programs\python\python310\lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.4.6)
Requirement already satisfied: decorator in .\appdata\local\programs\python\python310\lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<5,>=4->jupyterlab-execute-time) (5.3.1)
Requirement already satisfied: jedi>=0.16 in .\appdata\local\programs\python\python310\lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.20.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in .\appdata\local\programs\python\python310\lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<5,>=4->jupyterlab-execute-time) (3.0.53)
Requirement already satisfied: pygments>=2.4.0 in .\appdata\local\programs\python\python310\lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<5,>=4->jupyterlab-execute-time) (2.19.2)
Requirement already satisfied: stack_data in .\appdata\local\programs\python\python310\lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.6.3)
Requirement already satisfied: wcwidth>=0.1.4 in .\appdata\local\programs\python\python310\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.8.2)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in .\appdata\local\programs\python\python310\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.8.7)
Requirement already satisfied: MarkupSafe>=2.0 in .\appdata\local\programs\python\python310\lib\site-packages (from jinja2>=3.0.3->jupyterlab<5,>=4->jupyterlab-execute-time) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in .\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab<5,>=4->jupyterlab-execute-time) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in .\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab<5,>=4->jupyterlab-execute-time) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in .\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in .\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.30.0)
Requirement already satisfied: python-dateutil>=2.8.2 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client>=7.4.4->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyter-core->jupyterlab<5,>=4->jupyterlab-execute-time) (4.11.0)
Requirement already satisfied: python-json-logger>=2.0.4 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (4.1.0)
Requirement already satisfied: pyyaml>=5.3 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (6.0.3)
Requirement already satisfied: rfc3339-validator in .\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in .\appdata\local\programs\python\python310\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.1.1)
Requirement already satisfied: fqdn in .\appdata\local\programs\python\python310\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (1.5.1)
Requirement already satisfied: isoduration in .\appdata\local\programs\python\python310\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in .\appdata\local\programs\python\python310\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (3.1.1)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in .\appdata\local\programs\python\python310\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (1.1.0)
Requirement already satisfied: uri-template in .\appdata\local\programs\python\python310\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in .\appdata\local\programs\python\python310\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (25.10.0)
Requirement already satisfied: beautifulsoup4 in .\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (4.15.0)
Requirement already satisfied: bleach!=5.0.0 in .\appdata\local\programs\python\python310\lib\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (6.4.0)
Requirement already satisfied: defusedxml in .\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in .\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in .\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (3.3.4)
Requirement already satisfied: nbclient>=0.5.0 in .\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.11.0)
Requirement already satisfied: pandocfilters>=1.4.1 in .\appdata\local\programs\python\python310\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (1.5.1)
Requirement already satisfied: webencodings in .\appdata\local\programs\python\python310\lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.5.1)
Requirement already satisfied: tinycss2>=1.1.0 in .\appdata\local\programs\python\python310\lib\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in .\appdata\local\programs\python\python310\lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (2.22.1)
Requirement already satisfied: six>=1.5 in .\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=7.4.4->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab<5,>=4->jupyterlab-execute-time) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in .\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab<5,>=4->jupyterlab-execute-time) (2.6.1)
Requirement already satisfied: lark>=1.2.2 in .\appdata\local\programs\python\python310\lib\site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (1.3.1)
Requirement already satisfied: cffi>=1.0.1 in .\appdata\local\programs\python\python310\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (2.0.0)
Requirement already satisfied: pycparser in .\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (2.23)
Requirement already satisfied: soupsieve>=1.6.1 in .\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (2.9.1)
Requirement already satisfied: arrow>=0.15.0 in .\appdata\local\programs\python\python310\lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (1.4.0)
Requirement already satisfied: tzdata in .\appdata\local\programs\python\python310\lib\site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab<5,>=4->jupyterlab-execute-time) (2025.2)
Requirement already satisfied: executing>=1.2.0 in .\appdata\local\programs\python\python310\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<5,>=4->jupyterlab-execute-time) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in .\appdata\local\programs\python\python310\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<5,>=4->jupyterlab-execute-time) (3.0.2)
Requirement already satisfied: pure-eval in .\appdata\local\programs\python\python310\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<5,>=4->jupyterlab-execute-time) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

In [14]:
pip install pandas

Requirement already satisfied: pandas in .\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in .\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in .\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in .\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [52]:
import pandas as pd
data={
    'Name':['x','y','z'],
    'Age':[10,20,30]
}
df=pd.DataFrame(data)
df['Salary']=[10000,200000,300000]
df.drop('Salary',axis=1,inplace=True)
df

  Name  Age
0    x   10
1    y   20
2    z   30

In [43]:
df

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106
...,...,...,...,...,...,...,...,...
6430,45,28-09-2012,713173.95,0,64.88,3.997,192.013558,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,192.170412,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,192.308899,8.667

In [42]:
df

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106
...,...,...,...,...,...,...,...,...
6430,45,28-09-2012,713173.95,0,64.88,3.997,192.013558,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,192.170412,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,192.308899,8.667

In [25]:
import pandas as pd

In [34]:
df=pd.read_csv('Walmart_Sales.csv')
df.tail(7)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
6428,45,14-09-2012,702238.27,0,67.87,3.948,191.699850,8.684
6429,45,21-09-2012,723086.20,0,65.32,4.038,191.856704,8.684
6430,45,28-09-2012,713173.95,0,64.88,3.997,192.013558,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,192.170412,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,192.308899,8.667

In [29]:
df[Temperature]

NameError: name 'Temperature' is not defined

In [35]:
df

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106
...,...,...,...,...,...,...,...,...
6430,45,28-09-2012,713173.95,0,64.88,3.997,192.013558,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,192.170412,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,192.308899,8.667

In [40]:
df['Salary']=[133333333,222222222222,444444444444,222222,33333,2222222,11111,4444444,111111111,44444444]
df

ValueError: Length of values (10) does not match length of index (6435)

In [37]:
df

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106
...,...,...,...,...,...,...,...,...
6430,45,28-09-2012,713173.95,0,64.88,3.997,192.013558,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,192.170412,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,192.308899,8.667

In [59]:
df=pd.read_csv('Walmart_Sales.csv')

In [60]:
df.describe()

,Store,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
count,6435.000000,6.435000e+03,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000
mean,23.000000,1.046965e+06,0.069930,60.663782,3.358607,171.578394,7.999151
std,12.988182,5.643666e+05,0.255049,18.444933,0.459020,39.356712,1.875885
min,1.000000,2.099862e+05,0.000000,-2.060000,2.472000,126.064000,3.879000
25%,12.000000,5.533501e+05,0.000000,47.460000,2.933000,131.735000,6.891000
50%,23.000000,9.607460e+05,0.000000,62.670000,3.445000,182.616521,7.874000
75%,34.000000,1.420159e+06,0.000000,74.940000,3.735000,212.743293,8.622000
max,45.000000,3.818686e+06,1.000000,100.140000,4.468000,227.232807,14.313000

In [62]:
df

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106
...,...,...,...,...,...,...,...,...
6430,45,28-09-2012,713173.95,0,64.88,3.997,192.013558,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,192.170412,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,192.308899,8.667

In [63]:
df.isnull()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
6430,False,False,False,False,False,False,False,False
6431,False,False,False,False,False,False,False,False
6432,False,False,False,False,False,False,False,False
6433,False,False,False,False,False,False,False,False
6434,False,False,False,False,False,False,False,False

In [64]:
df.isnull().sum()

Store           0
Date            0
Weekly_Sales    0
Holiday_Flag    0
Temperature     0
Fuel_Price      0
CPI             0
Unemployment    0
dtype: int64

In [68]:
df.head(5)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [77]:
new_value=df.groupby("Fuel_Price")['Temperature'].mean()
print(new_value)

Fuel_Price
2.472    45.660000
2.513    80.580000
2.514    42.822143
2.520    50.870000
2.533    82.290000
           ...
4.294    66.710000
4.301    68.758333
4.308    86.730000
4.449    71.158333
4.468    74.486667
Name: Temperature, Length: 892, dtype: float64

In [95]:
pip install html5lib

Requirement already satisfied: html5lib in .\appdata\local\programs\python\python310\lib\site-packages (1.1)
Requirement already satisfied: six>=1.9 in .\appdata\local\programs\python\python310\lib\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in .\appdata\local\programs\python\python310\lib\site-packages (from html5lib) (0.5.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [103]:
url="https://media.apps.chicagotribune.com/tables/example.html"
df=pd.read_html(url)
df[0]

,Bank,State,Closing Date,Our Coverage,Federal Regulators,Public Enforcement Documents
0,Bank of Clark County,Washington,1/16/2009,NaN,FDIC,NaN
1,National Bank of Commerce,Illinois,1/16/2009,NaN,OCC,NaN
2,1st Centennial Bank,California,1/23/2009,NaN,FDIC,NaN
3,MagnetBank,Utah,1/30/2009,NaN,FDIC,Cease and Desist (10/1/08)
4,Ocala National Bank,Florida,1/30/2009,NaN,OCC,Consent Order (2/14/08)
...,...,...,...,...,...,...
135,Imperial Capital Bank,California,12/18/2009,NaN,FDIC,Cease and Desist 2-17-09
136,Citizens State Bank,Michigan,12/18/2009,NaN,FDIC,Cease and Desist 10-15-09
137,New South Federal Savings Bank,Alabama,12/18/2009,NaN,OTS,Cease and Desist 5-15-09
138,Peoples First Community Bank,Florida,12/18/2009,NaN,OTS,Cease and Desist 2-11-09
139,Independent Bankers' Bank,Illinois,12/18/2009,NaN,FRB,Written Agreement 7-7-09

In [104]:
!pip install matplotlib

Requirement already satisfied: matplotlib in .\appdata\local\programs\python\python310\lib\site-packages (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in .\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in .\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in .\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in .\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (2.2.6)
Requirement already satisfied: packaging>=20.0 in .\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in .\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=3 in .\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in .\appdata\local\programs\python\python310\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in .\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [110]:
!python.exe -m pip install --upgrade pip

Requirement already satisfied: pip in .\appdata\local\programs\python\python310\lib\site-packages (26.2.1)