In [2]:
import pandas as pd
import numpy as np

In [3]:
student_data=[
  [1, 15],
  [2, 11],
  ['null', 11],
  [4, 20]
]
df=pd.DataFrame(student_data)

In [4]:
df=pd.DataFrame(student_data).rename(columns={0:"x",1:"y"})

In [5]:
df.head()

      x   y
0     1  15
1     2  11
2  null  11
3     4  20

In [15]:
df['x'].drop(df['x'].isnull())

Series([], Name: x, dtype: object)

In [16]:
df

Empty DataFrame
Columns: [x, y]
Index: []